### ISSUE TITLE
Seeking Guidance: ImportError for libcudnn.so.8 in visual_robot_localization Project

### ISSUE THREAD

**Issue by i-kj** [lasuomela/visual_robot_localization#4]
Hello,

I am currently working on the visual_robot_localization project and have encountered an issue I'm unable to resolve. Specifically, I'm facing an ImportError related to libcudnn.so.8 when attempting to run the ./do_SfM.sh script. The traceback suggests that the torch import in SfM_from_camera_poses.py is failing due to this.

Here is the error message for reference:

ImportError: libcudnn.so.8: cannot open shared object file: No such file or directory

Steps Taken:

    The Docker container is built and runs without errors.
    colcon build also completes without errors.
    Checked that CUDA and cuDNN libraries are available in the Docker container. However, I was not able to locate them using ls /usr/local/cuda/lib64 and ls /usr/lib/x86_64-linux-gnu/.
    Tried explicitly adding library paths in the Python script but to no avail.
    
    Environment:

    Ubuntu 20.4
    CUDA:
    nvcc: NVIDIA (R) Cuda compiler driver
    Copyright (c) 2005-2019 NVIDIA Corporation
    Built on Sun_Jul_28_19:07:16_PDT_2019
    Cuda compilation tools, release 10.1, V10.1.243
    cuDNN [version]:
    Python 3.9
    Docker [version]: Docker version 24.0.5, build ced0996
    Torch [version]: 1.12.1+cu102

I would be extremely grateful if anyone could provide guidance on resolving this issue. Any advice or troubleshooting tips would be much appreciated.

Thank you for your time and assistance.

Best regards,
KJ

**Comment by lasuomela** [comment]
Hello,

I suspect something has gone wrong with your docker build, since the Dockerfile copies the cuda files into /usr/local/cuda.

I hadn't built the image in some time, and seems like the base cuda image tag was out of date. I updated it (see 2cf955e4a7bcfe38bb6b7cc88106a5e00ce64f96), so you might want to pull the commit and rebuild the image.

Let me know if it works.

Br,
Lauri

**Comment by i-kj** [comment]
Hello Lauri,
Thank you so much for your reply. Yes the new Dockerfile build was successful and I was able to launch testing ./do_SfM.sh but the reconstruction of scene from test folder was not as I intended it to be. 

./visualize_colmap.sh

![Colmap](https://github.com/lasuomela/visual_robot_localization/assets/141944156/8e202e77-4bac-4c97-bd03-64cf9a5dd5d2)

Can you please clarify this?

I was also able to launch the ros2 nodes and test the visual_pose_estimator successfully. 


----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
Type: visual_localization_interfaces/msg/VisualPoseEstimate
**ros2 topic info /carla/ego_vehicle/visual_pose_estimate**
Publisher count: 2
Subscription count: 0

**ros2 topic list**
/carla/ego_vehicle/rgb_front/image
/carla/ego_vehicle/visual_pose_estimate
/clock
/parameter_events
/rosout

Can you please confirm if everything works as intended? 


Thanks.

**Comment by lasuomela** [comment]
Hello,

Sorry for the delay. Everything works as it should, based on your posted image. With just a few images in the test folder, the reconstruction will not look very pretty.

Br,
Lauri
